#!/usr/bin/env bash
# ---------------------------------------------
# Script   : pegadinha
# Descrição: brincadeira para treinar a concatenação de strings.
# Versão   : 0.1
# Autor    : Jardson Baia
# Data	   : 26/04/2021
# Licença  : GNU/GPL v3.0
# ---------------------------------------------
# Uso: ./pegadinha ou caminho/pegadinha
# ---------------------------------------------

read -p "Digite um nome: " nome
read -p "Digite o nome de uma revista: " revista
read -p "Digite o nome de uma peça de roupa: " roupa

echo "
Você escolheu $nome, $revista e $roupa!
"

read -p "Digite um número de 1 a 3: " numero

frase[1]="$nome saiu na capa da $revista só de $roupa!"
frase[2]="$nome só consegue ler a $revista usando $roupa!"
frase[3]="$nome aprendeu na revista $revista que usar $roupa é legal!"

echo "
${frase[$numero]}
"

exit 0

